name: X2DRR
channels:
  - https://repo.anaconda.com/pkgs/msys2
  - https://repo.anaconda.com/pkgs/free
  - https://repo.anaconda.com/pkgs/main
  - https://conda.anaconda.org/conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.11.4=haa95532_0
  - libffi=3.4.4=hd77b12b_1
  - libzlib=1.3.1=h02ab6af_0
  - openssl=3.0.18=h543e019_0
  - pip=25.3=pyhc872135_0
  - python=3.11.7=he1021f5_0
  - setuptools=80.9.0=py311haa95532_0
  - sqlite=3.51.0=hda9a48d_0
  - tk=8.6.15=hf199647_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py311haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - anyio==4.12.0
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.4.0
      - asttokens==3.0.1
      - attrs==25.4.0
      - beautifulsoup4==4.14.3
      - bleach==6.3.0
      - certifi==2025.11.12
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - click==8.3.1
      - cmcrameri==1.9
      - cmocean==4.0.3
      - colorama==0.4.6
      - colorcet==3.1.0
      - comm==0.2.3
      - contourpy==1.3.3
      - cycler==0.12.1
      - decorator==5.2.1
      - defusedxml==0.7.1
      - deprecated==1.3.1
      - diffdrr==0.5.0
      - einops==0.8.1
      - executing==2.2.1
      - fastcore==1.9.5
      - fastjsonschema==2.21.2
      - filelock==3.19.1
      - fonttools==4.60.1
      - fqdn==1.5.1
      - frozenlist==1.8.0
      - fsspec==2025.9.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==1.2.3
      - humanize==4.15.0
      - idna==3.11
      - imageio==2.37.2
      - importlib-resources==6.5.2
      - ipython==9.8.0
      - ipython-pygments-lexers==1.1.1
      - ipywidgets==8.1.8
      - isoduration==20.11.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - joblib==1.5.2
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter-client==8.7.0
      - jupyter-core==5.9.1
      - jupyter-events==0.12.0
      - jupyter-server==2.17.0
      - jupyter-server-proxy==4.4.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab-pygments==0.3.0
      - jupyterlab-widgets==3.0.16
      - kiwisolver==1.4.9
      - kornia==0.8.2
      - kornia-rs==0.1.10
      - lark==1.3.1
      - markdown-it-py==4.0.0
      - markupsafe==2.1.5
      - matplotlib==3.10.7
      - matplotlib-inline==0.2.1
      - mdurl==0.1.2
      - meshio==5.3.5
      - mistune==3.1.4
      - more-itertools==10.8.0
      - mpmath==1.3.0
      - msgpack==1.1.2
      - multidict==6.7.0
      - nbclient==0.10.3
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.5
      - nibabel==5.3.3
      - numpy==2.2.6
      - opencv-python==4.12.0.88
      - overrides==7.7.0
      - packaging==25.0
      - pandas==2.3.3
      - pandocfilters==1.5.1
      - parso==0.8.5
      - pillow==11.3.0
      - platformdirs==4.5.1
      - pooch==1.8.2
      - prometheus-client==0.23.1
      - prompt-toolkit==3.0.52
      - propcache==0.4.1
      - pure-eval==0.2.3
      - pycparser==2.23
      - pydicom==3.0.1
      - pygments==2.19.2
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - python-json-logger==4.0.0
      - pytorch-msssim==1.0.0
      - pytz==2025.2
      - pyvista==0.46.4
      - pywinpty==3.0.2
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - referencing==0.37.0
      - requests==2.32.5
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rich==14.2.0
      - rpds-py==0.30.0
      - safetensors==0.7.0
      - scikit-learn==1.8.0
      - scipy==1.16.3
      - scooby==0.11.0
      - seaborn==0.13.2
      - send2trash==1.8.3
      - shellingham==1.5.4
      - simpervisor==1.0.0
      - simpleitk==2.5.3
      - six==1.17.0
      - soupsieve==2.8.1
      - stack-data==0.6.3
      - sympy==1.13.1
      - terminado==0.18.1
      - threadpoolctl==3.6.0
      - timm==1.0.22
      - tinycss2==1.4.0
      - torch==2.5.1+cu121
      - torchaudio==2.5.1+cu121
      - torchio==0.21.1
      - torchsummary==1.5.1
      - torchvision==0.20.1+cu121
      - tornado==6.5.4
      - tqdm==4.67.1
      - traitlets==5.14.3
      - trame==3.12.0
      - trame-client==3.11.2
      - trame-common==1.1.0
      - trame-server==3.9.0
      - trame-vtk==2.10.1
      - trame-vuetify==3.2.0
      - typer==0.20.1
      - typer-slim==0.20.1
      - typing-extensions==4.15.0
      - tzdata==2025.3
      - uri-template==1.3.0
      - urllib3==2.6.2
      - vtk==9.5.2
      - wcwidth==0.2.14
      - webcolors==25.10.0
      - webencodings==0.5.1
      - websocket-client==1.9.0
      - widgetsnbextension==4.0.15
      - wrapt==2.0.1
      - wslink==2.5.0
      - yarl==1.22.0
prefix: F:\Files\PythonFiles\anaconda\envs\X2DRR
