name: X2DRR

channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  # ===== 基础环境 =====
  - python=3.11.7
  - pip=25.3
  - setuptools
  - wheel

  # ===== PyTorch + CUDA =====
  - pytorch=2.5.1
  - torchvision=0.20.1
  - torchaudio=2.5.1
  - pytorch-cuda=12.1
  - cuda-runtime=12.1

  # ===== 科学计算 & 数值库 =====
  - numpy=2.2.6
  - scipy=1.16.3
  - pandas=2.3.3
  - scikit-learn=1.8.0
  - matplotlib=3.10.7
  - seaborn=0.13.2

  # ===== 医学影像 / 三维处理 =====
  - simpleitk=2.5.3
  - nibabel=5.3.3
  - meshio=5.3.5
  - vtk=9.5.2
  - pyvista=0.46.4

  # ===== 其他常用工具 =====
  - tqdm=4.67.1
  - pyyaml
  - pillow=11.3.0
  - opencv=4.12.0

  # ===== pip 依赖 =====
  - pip:
      # --- DRR & 医学影像 ---
      - diffdrr==0.5.0
      - pydicom==3.0.1
      - torchio==0.21.1

      # --- 深度学习工具 ---
      - einops==0.8.1
      - timm==1.0.22
      - kornia==0.8.2
      - pytorch-msssim==1.0.0
      - lpips==0.1.4

      # --- 可视化 / 交互 ---
      - rich==14.2.0
      - ipython==9.8.0
      - ipywidgets==8.1.8

      # --- 实验与日志 ---
      - tqdm
